import React from "react";

const SelectedBudget = (budget) => {

    return (
        <div className="container">
            <h3>Selected Budget</h3>
            <div>
                {/* Autogenerated Budget Content */}
            </div>
        </div>
    );
};

export default SelectedBudget;